# What are we doing here? Oh yes, building things.
# I told you I was ill. But not as ill as this build system.

cmake_minimum_required(VERSION 3.10) # We need at least 3.10, or else the computer will explode.

project(HelloTea) # A project about tea. How very British.

# Add the executable, quick, before the nurse comes back!
add_executable(hello hello.cpp)

# And now, we wait. Or compile. One of the two.
# Probably both, knowing my luck.
# Configuring done. Now go away.
